server:
  port: 8181

spring:
  #  连接数据库的数据源
  datasource:
    username: root
    password: "0118"
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/pan_download?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  #文件上传的配置
  servlet:
    multipart:
      enabled: true
      #允许上传的单个文件大小
      max-file-size: 5GB
      #每次上传请求允许的文件总大小
      max-request-size: 6GB

mybatis:
  mapper-locations: classpath:mapper/*.xml


